/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wgs.launcher;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aamir
 */
public class mainmenu extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public mainmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPlayHalo = new javax.swing.JLabel();
        btnPlayMC = new javax.swing.JLabel();
        btnCommunity = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Woodlands Gaming Society Launcher");
        setBackground(new java.awt.Color(255, 51, 51));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(495, 695));
        setMinimumSize(new java.awt.Dimension(495, 695));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(495, 695));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        jPanel2.setMaximumSize(new java.awt.Dimension(357, 400));
        jPanel2.setMinimumSize(new java.awt.Dimension(357, 400));
        jPanel2.setName(""); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(357, 400));

        btnPlayHalo.setBackground(new java.awt.Color(255, 65, 52));
        btnPlayHalo.setForeground(new java.awt.Color(255, 255, 255));
        btnPlayHalo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPlayHalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wgs/launcher/btn_PlayHalo.png"))); // NOI18N
        btnPlayHalo.setMaximumSize(new java.awt.Dimension(357, 75));
        btnPlayHalo.setMinimumSize(new java.awt.Dimension(357, 75));
        btnPlayHalo.setPreferredSize(new java.awt.Dimension(357, 75));
        btnPlayHalo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayHaloMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlayHaloMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPlayHaloMouseReleased(evt);
            }
        });

        btnPlayMC.setBackground(new java.awt.Color(255, 65, 52));
        btnPlayMC.setForeground(new java.awt.Color(255, 255, 255));
        btnPlayMC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPlayMC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wgs/launcher/btn_PlayMC.png"))); // NOI18N
        btnPlayMC.setMaximumSize(new java.awt.Dimension(357, 75));
        btnPlayMC.setMinimumSize(new java.awt.Dimension(357, 75));
        btnPlayMC.setPreferredSize(new java.awt.Dimension(357, 75));
        btnPlayMC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMCMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlayMCMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPlayMCMouseReleased(evt);
            }
        });

        btnCommunity.setBackground(new java.awt.Color(255, 65, 52));
        btnCommunity.setForeground(new java.awt.Color(255, 255, 255));
        btnCommunity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCommunity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wgs/launcher/btn_Community.png"))); // NOI18N
        btnCommunity.setMaximumSize(new java.awt.Dimension(357, 75));
        btnCommunity.setMinimumSize(new java.awt.Dimension(357, 75));
        btnCommunity.setPreferredSize(new java.awt.Dimension(357, 75));
        btnCommunity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCommunityMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCommunityMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCommunityMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCommunityMouseReleased(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 65, 52));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wgs/launcher/btn_Exit.png"))); // NOI18N
        btnExit.setToolTipText("");
        btnExit.setMaximumSize(new java.awt.Dimension(357, 75));
        btnExit.setMinimumSize(new java.awt.Dimension(357, 75));
        btnExit.setPreferredSize(new java.awt.Dimension(357, 75));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPlayHalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlayMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnPlayHalo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPlayMC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 700));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wgs/launcher/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 700));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnPlayHaloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayHaloMouseClicked
        
    }//GEN-LAST:event_btnPlayHaloMouseClicked

    private void btnPlayHaloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayHaloMousePressed
        btnPlayHalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wgs/launcher/pressedbtn_PlayHalo.png")));
    }//GEN-LAST:event_btnPlayHaloMousePressed

    private void btnPlayHaloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayHaloMouseReleased
        btnPlayHalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wgs/launcher/btn_PlayHalo.png")));
        try {
            Process p = new ProcessBuilder("src\\wgs\\launcher\\test.exe").start();
        } catch (IOException ex) {
            Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPlayHaloMouseReleased

    private void btnPlayMCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMCMousePressed
        btnPlayMC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wgs/launcher/pressedbtn_PlayMC.png")));
    }//GEN-LAST:event_btnPlayMCMousePressed

    private void btnPlayMCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMCMouseReleased
        btnPlayMC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wgs/launcher/btn_PlayMC.png")));
        try {
            Process p = new ProcessBuilder("src\\wgs\\launcher\\test.exe").start();
        } catch (IOException ex) {
            Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPlayMCMouseReleased

    private void btnCommunityMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCommunityMousePressed
        btnCommunity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wgs/launcher/pressedbtn_Community.png")));
    }//GEN-LAST:event_btnCommunityMousePressed

    private void btnCommunityMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCommunityMouseReleased
        btnCommunity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wgs/launcher/btn_Community.png")));
        try {
            Desktop.getDesktop().open(new File(new File(System.getProperty("user.home")), "Videos"));
        } catch (IOException ex) {
            Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCommunityMouseReleased

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wgs/launcher/pressedbtn_Exit.png")));
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wgs/launcher/btn_Exit.png")));
    }//GEN-LAST:event_btnExitMouseReleased

    private void btnPlayMCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMCMouseClicked
        
    }//GEN-LAST:event_btnPlayMCMouseClicked

    private void btnCommunityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCommunityMouseEntered
    
    }//GEN-LAST:event_btnCommunityMouseEntered

    private void btnCommunityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCommunityMouseClicked

    }//GEN-LAST:event_btnCommunityMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

       (new commandReaderThread()).start();
        try {
            //sets look and feel
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            //catches exception
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCommunity;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnPlayHalo;
    private javax.swing.JLabel btnPlayMC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}